site_name: 2022 June All-Hands Meeting

theme:
  name: material
  palette:
    primary: white

docs_dir: ./docs

nav:
    - Home: index.md
    - Code of Conduct: CODEOFCONDUCT.md
    - Contact: CONTACT.md
